kakao-tech-campus-3rd-step3/Team15_BE

src/main/java/katecam/hyuswim/post/dto/PostDetailResponse.java
src/main/java/katecam/hyuswim/post/dto/PostListResponse.java
src/main/java/katecam/hyuswim/user/User.java
src/main/java/katecam/hyuswim/user/controller/UserController.java
src/main/java/katecam/hyuswim/user/dto/JwtTokenRequest.java
src/main/java/katecam/hyuswim/user/dto/JwtTokenResponse.java
src/main/java/katecam/hyuswim/user/dto/LoginRequest.java
src/main/java/katecam/hyuswim/user/dto/SignupRequest.java
src/main/java/katecam/hyuswim/user/jwt/JwtUtil.java
src/main/java/katecam/hyuswim/user/repository/UserRepository.java
src/main/java/katecam/hyuswim/user/service/UserService.java

- @DaTa 제거
- @NoArgsConstructor 제거
- SignupRequestDto에서 User만드는 함수제거
- @DaTa 제거
- @NoArgsConstructor 제거
- SignupRequestDto에서 User만드는 함수제거
- Closes #25 
- @DaTa 제거
- @NoArgsConstructor 제거
- SignupRequestDto에서 User만드는 함수제거

refactor: dto 꼭필요한 어노테이션만 사용하게 변경

---

src/main/java/katecam/hyuswim/common/error/ErrorCode.java
src/main/java/katecam/hyuswim/user/service/UserService.java

- 로그인 에러코드 변수명 변경
- 로그인 에러 코드 변수명을 LOGIN_FAILED로 변경
- Closes #49 
-

refactor: 로그인 에러 코드 변수명을 LOGIN_FAILED로 변경

---

src/main/java/katecam/hyuswim/comment/repository/CommentRepository.java

- CommentRespository 오타를 CommentRepository로 수정
- Closes #56 
X

fix: CommentRespository 오타를 CommentRepository로 수정

---

.github/workflows/deploy.yml
env.example
src/main/resources/application-dev.yml

- 코드 스타일 검증 제거
- 코드 스타일 검증 제거
- Closes #96 
-

[Refactor] deploy.yml 코드 스타일 검증 제거

---

build.gradle

- 빌드 시 코드 스타일 검증을 진행해서 안될 시에 빌드가 실패 -> 스킵
- 빌드 시 코드 스타일 검증 스킵
- Closes #99 
-

[Fix] 빌드 시 코드 스타일 미검증

---

src/main/java/katecam/hyuswim/auth/config/DevSecurityConfig.java

- DevSecurityCofig 설정
- DevSecurityCofig 추가
- 임시로 api/** 뒤로 나오는 get 요청 다 허용
- Closes #110 
-

feat :DevSecurityCofig 설정 추가

---

src/main/java/katecam/hyuswim/user/User.java
src/main/java/katecam/hyuswim/user/controller/MyPageController.java
src/main/java/katecam/hyuswim/user/service/MyPageService.java

- 좋아요 알림 버튼 구현
- 댓글 알림 구현
유저테이블에 commentNotificationEnabled, likeNotificationEnabled 생성
- Closes #이슈번호
-

feat: 좋아요알림,댓글알림 버튼 구현

---

.github/workflows/deploy.yml
.github/workflows/lint-workflows.yml

- GitHub Actions 배포 workflow yml 문법 오류 수정
- deploy.yml 내 잘못된 문법 수정
- 워크 플로우 문법 검증용 Lint Job 추가
- Closes #이슈번호
-

fix : GitHub Actions 배포 workflow yml 문법 오류 수정

---

src/main/java/katecam/hyuswim/user/controller/MyPageController.java
src/main/java/katecam/hyuswim/user/dto/mypage/MyCommentResponse.java
src/main/java/katecam/hyuswim/user/dto/mypage/MyLikedPostResponse.java
src/main/java/katecam/hyuswim/user/dto/mypage/MyOverviewResponse.java
src/main/java/katecam/hyuswim/user/dto/mypage/MyPostListResponse.java
src/main/java/katecam/hyuswim/user/service/MyPageService.java

- 오버뷰 응답값변경
- 내게시글 응답값변경
- 내댓글 응답값변경
- 내좋아요 응답값변경
- <img width="1376" height="676" alt="image" src="https://github.com/user-attachments/assets/ce0640d3-087b-4e13-8b76-572385626e67" />
- <img width="1400" height="860" alt="image" src="https://github.com/user-attachments/assets/ed2cb836-ea4c-4ab7-810e-12660ea44937" />
- <img width="1365" height="984" alt="image" src="https://github.com/user-attachments/assets/d801f458-5696-470e-840e-4ff8d3f3a637" />
- <img width="1362" height="898" alt="image" src="https://github.com/user-attachments/assets/21bf76de-89e7-49ce-9abb-557526792cd9" />
- Closes #이슈번호
-

feat: 내 활동 내역 구현

---

.github/workflows/deploy.yml

- FRONTEND_URL Secrets 값 누락 방지를 위한 따옴표 감싸기 적용
-
- Closes #이슈번호
-

fix: FRONTEND_URL Secrets 값 누락 방지를 위한 따옴표 감싸기 적용

---

docker-compose.yml

- 깃허브 액션 시크릿키 수정
- 깃허브 액션 시크릿키 수정
- Closes #224 
-

[Fix] Github action 시크릿키 수정

---

.github/workflows/deploy.yml
docker-compose.yml

- 레디스 포트 환경변수 중복 주입 제거
- 레디스 포트 환경변수 중복 주입 제거
- Closes #226 
-

[Refactor] 레디스 포트 환경변수 중복 주입 제거

---

.github/workflows/deploy.yml

- deploy.yml 표현식 공백 제거 및 scp-action source 파싱 오류 수정
- 
- Closes #이슈번호
-

fix: deploy.yml 공백 제거 및 파일 전송 오류 수정

---

.github/workflows/deploy.yml

- 다중 파일 전송 시 source 설정 오류 수정
- 
- Closes #이슈번호
-

fix: 다중 파일 전송 시 source 설정 오류 수정

---

.github/workflows/deploy.yml

- scp-action tar 에러 해결 위해 ssh-action + scp로 교체
-
- Closes #이슈번호
-

fix: scp-action tar 에러 해결 위해 ssh-action + scp로 교체

---

.github/workflows/deploy.yml

- deploy.yml의 SCP 파일 전송 오류 해결 및 CI/CD 구조 개선
- SCP 파일 전송 존재 검증 로직 추가
- PR 빌드 검증과 Merge 배포 작업 분리
- 와... 검증할때마다 브런치 만들고 미쳐버리는 줄 알았는데 PR 상태로 체크 가능하게도 가능하네요 아무래도 돌릴 때마다 머지하고 브런치 새로 파서 테스트 한다는게 너무 원시적이긴 했네요
- 배포 파이프라인 안정화 및 테스트 의존성 해결
- Closes #213 
-

chore: deploy.yml의 SCP 파일 전송 오류 해결 및 CI/CD 구조 개선

---

.github/workflows/deploy.yml

- GitHub Secrets 주입 방식 수정 및 .env 자동 삭제 적용
- 
- Closes #213 
-

ci: GitHub Secrets 주입 방식 수정 및 .env 자동 삭제 적용

---

.github/workflows/deploy.yml

- 배포 시 Gradle 빌드 및 Docker Compose 실행 자동화
-
- Closes #213 
-

ci: 배포 시 Gradle 빌드 및 Docker Compose 실행 자동화

---

src/main/java/katecam/hyuswim/common/config/AppProperties.java

- AppProperties 바인딩 오류 수정
- 
- Closes #213 
-

fix: AppProperties 바인딩 오류 수정

---

src/main/java/katecam/hyuswim/auth/util/RedirectUrlBuilder.java
src/main/java/katecam/hyuswim/common/config/DevSecurityConfig.java

- 변경/추가된 기능 간단 요약
- 구체적으로 무엇을 어떻게 변경했는지 작성
- Closes #이슈번호
-

fix: AppProperties 변경에 따른 참조 코드 수정

---

.github/workflows/deploy.yml

- deploy.yml 에서 .env.dev에서 .dev 제거
- 
- Closes #213 
-

chore: deploy.yml 에서 .env.dev에서 .dev 제거

---

src/main/resources/application.yml

- 환경변수 매핑 개선: APP_PORT와 SPRING_PROFILE 적용
-
- Closes #213 
-

fix: 환경변수 매핑 개선: APP_PORT와 SPRING_PROFILE 적용

---

src/main/java/katecam/hyuswim/auth/domain/UserAuth.java
src/main/java/katecam/hyuswim/auth/repository/UserAuthRepository.java
src/main/java/katecam/hyuswim/common/error/ErrorCode.java
src/main/java/katecam/hyuswim/user/controller/MyPageController.java
src/main/java/katecam/hyuswim/user/dto/mypage/MyProfileEditResponse.java
src/main/java/katecam/hyuswim/user/dto/mypage/PasswordUpdateRequest.java
src/main/java/katecam/hyuswim/user/service/MyPageService.java

- 이메일주소변경
- 비밀번호변경
- 내프로필 수정조회 
- 이메일주소변경시 인증번호 요청할수있게함
- 이메일주소변경시 인증번호가 일치하면 변경가능하게함
- 현재 비밀번호가 올바를경우 비밀번호를 변경할수있게함
- Closes #이슈번호
-

feat: 이메일주소변경, 비밀번호변경, 내프로필 수정조회 구현

---

src/main/resources/application.yml

- katecam.hyuswim 패키지 로그 레벨 설정 추가
- 
- Closes #265 
-

chore: katecam.hyuswim 패키지 로그 레벨 설정 추가

---

.github/workflows/deploy.yml

- 불필요한 fi 삭제
- 
- Closes #이슈번호
-

chore: 불필요한 fi 삭제

---

src/main/java/katecam/hyuswim/user/controller/MyPageController.java
src/main/java/katecam/hyuswim/user/dto/mypage/BadgeCollectionResponse.java
src/main/java/katecam/hyuswim/user/service/MyPageService.java

- 뱃지컬렉션 조회
-  획득뱃지
- 미획득뱃지
- 전체뱃지 나오게 구현
```
{
"earnedBadges": [
{
"name": "YOUR_BADGE_NAME",
"kind": "LOVE_EVANGELIST",
"iconUrl": "YOUR_ICON_URL",
"earnedAt": "2025-10-05T02:18:48"
}
],
"unearnedBadges": [
{
"name": "YOUR_BADGE_NAME",
"kind": "DILIGENT_COMMENTER",
"iconUrl": "YOUR_ICON_URL"
},
{
"name": "YOUR_BADGE_NAME",
"kind": "MISSION_KILLER",
"iconUrl": "YOUR_ICON_URL"
},
{
"name": "YOUR_BADGE_NAME",
"kind": "PERFECT_ATTENDANCE",
"iconUrl": "YOUR_ICON_URL"
}
],
"allBadges": [
{
"name": "YOUR_BADGE_NAME",
"kind": "LOVE_EVANGELIST",
"iconUrl": "YOUR_ICON_URL"
},
{
"name": "YOUR_BADGE_NAME",
"kind": "DILIGENT_COMMENTER",
"iconUrl": "YOUR_ICON_URL"
},
{
"name": "YOUR_BADGE_NAME",
"kind": "MISSION_KILLER",
"iconUrl": "YOUR_ICON_URL"
},
{
"name": "YOUR_BADGE_NAME",
"kind": …
```

feat: 뱃지컬렉션 조회 api 구현
